# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk'

# Website info
name: "Parth"
description: "Oh, I'm sorry did I break your concentration!"

# Author's info
author: 'Parth Nagori'
# edit 'categories' in the front matter of every post to match this username
nickname: Parth
bio: 'A Graduate Student studying Computer Science at North Carolina State University'
location: 'Raleigh, NC'
url: 'https://parthnagori.github.io/'
image: 'assets/images/casper.png'

short_url: 'parthnagori.github.io'
google_analytics: UA-107715238-1
disqus: username
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: '/'

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: parthnagori
repo: https://github.com/parthnagori/parthnagori.github.io/
branch: branch_1
relative_source: ../ 
destination: ../gh_pages 
production_url:  https://parthnagori.github.io/
source_url: https://github.com/parthnagori/parthnagori.github.io/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
